export const metadata = {
  title: "Next Pizza | Доска",
  description: "Generated by Next.js",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main>
      dashboard HEADER
      {children}
    </main>
  );
}
